# Generated by Django 4.2.21 on 2025-11-08 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_coins_student_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Qo'shimcha telefon raqami"),
        ),
        migrations.AlterField(
            model_name='user',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profil rasmi'),
        ),
    ]
