# Generated by Django 4.2.21 on 2025-11-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_transactions_student_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Maxsulot nomi')),
                ('product_price', models.IntegerField(max_length=1000, verbose_name='Maxsulot narxi')),
                ('amount', models.IntegerField(max_length=10000, verbose_name='Miqdori')),
                ('product_image', models.ImageField(upload_to='products/', verbose_name='Maxsulot rasmi')),
            ],
        ),
    ]
