# Generated by Django 4.2.21 on 2025-11-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
