# Generated by Django 4.2.21 on 2025-11-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriyasi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='item_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='item',
            name='info',
            field=models.TextField(verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='total',
            field=models.IntegerField(verbose_name='Mavjud soni'),
        ),
    ]
