# Generated by Django 4.2.21 on 2025-11-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_item_category_alter_item_image_alter_item_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
