# Generated by Django 4.2.21 on 2025-11-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='Umumiy', max_length=100, null=True, verbose_name='Kategoriyasi'),
        ),
    ]
