# Generated by Django 4.2.21 on 2025-11-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('content', models.TextField(max_length=500, verbose_name='Kontent')),
                ('news_date', models.DateTimeField(auto_now_add=True, verbose_name='Nashr qilingan sana')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Rasm')),
            ],
        ),
    ]
