# Generated by Django 4.2.21 on 2025-11-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-news_date']},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='news_image',
        ),
    ]
