# Generated by Django 4.2.21 on 2025-11-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_news_options_rename_image_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Kontent'),
        ),
    ]
