# Generated by Django 4.2.21 on 2025-11-15 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='maxsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.item'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='miqdor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
